version: 0.0
os: linux
files:
  - source: ./ocdl/cx/target/cx-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/ocdl/
  - source: ./ocdl/deploy_script/stopApp.sh
    destination: /home/ubuntu/ocdl/
  - source: ./ocdl/deploy_script/startApp.sh
    destination: /home/ubuntu/ocdl/
  - source: ./appspec.yml
    destination: /home/ubuntu/ocdl/
hooks:
  ApplicationStop:
    - location: deploy_script/stopApp.sh
      timeout: 300
  ApplicationStart:
    - location: deploy_script/startApp.sh
      runas: ubuntu
      timeout: 300
